### PR TITLE
Make hemp usable as fuel

### PR DESCRIPTION
**Pull request by FaceDeer**

### CODE REVIEW

**Comment by HybridDog** [comment]
You can use furnace_burntime in the nodedef.

**Comment by FaceDeer** [comment]
furnace_burntime has been deprecated since 2012: https://forum.minetest.net/viewtopic.php?id=831

The register_item code in builtin\game\register.lua does handle furnace_burntime by automatically creating a fuel recipe based off of it, but furnace_burntime isn't in any of the documentation any more so I don't think it's a good idea to rely on this legacy support in new mod code.

**Comment by HybridDog** [comment]
Thanks for this information. After l discovered it, l used it everywhere in my mods because it's less code than writing a crafting recipe… l think l'll change them when problems occur.

**Comment by FaceDeer** [comment]
I have to admit, I had a few minutes of panic when you mentioned that furnace_burntime thing. A while back I wrote the [Simplecrafting](https://github.com/minetest-mods/simplecrafting_lib) library in an effort to streamline Minetest's crafting system and make it less error-prone, and in the process I had to write code that understood every conceivable quirk and undocumented weirdness of the existing crafting system so that it could convert all "legacy" recipes to its own internal format. It was a gruelling process and I thought I'd missed a major chunk of fuel. Fortunately the legacy handling in register.lua was feeding furnace_burntime recipes to my code anyway, so panic averted. :)

Anyway, this is your mod and furnace_burntime does still work in the current version. So if you really prefer it I can switch my pull request over to using that.

**Comment by HybridDog** [comment]
No, it's not my mod. l don't prefer furnace_burntime since l know it's deprecated.
‫@pithydon, ‭pls merge this‪

**Pull request merged**
